import {StyleSheet} from 'react-native';

const StyleMaincomponent = StyleSheet.create({
  background_views: {
    alignItems: 'center',
    backgroundColor: '#FAC983',
    padding: 80,
    justifyContent: 'center',
    flex: 1,
  },
  texts: {
    alignContent: 'center',
    right: 80,
  },
  texts2: {
    paddingTop: 10,
    fontSize: 15,
    paddingLeft: 30,
  },
  space: {
    marginVertical: 100,
  },
  buttons: {
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: 'white',
    width: 350,
    height: 50,
    // justifyContent: 'center',
    flexDirection: 'row',
  },
  button_logout: {
    borderRadius: 12,
    justifycontent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    backgroundColor: '#E35205',
    width: 300,
    //padding: 100,
    // margin:20,
  },
  logos1: {
    height: 20,
    width: 20,
    alignItems: 'center',
    resizeMode: 'stretch',
    marginRight: 40,
  },
  editcards: {
    height: 20,
    width: 25,
    alignItems: 'center',
    justifycontent: 'space-between',
  },
  help: {
    resizeMode: 'cover',
    height: 20,
    width: 20,
    alignItems: 'center',
  },
  aboutus: {
    resizeMode: 'cover',
    height: 20,
    width: 20,
    alignItems: 'center',
  },
  user: {
    position: 'absolute',
    top: 30,
    left: 20,
    resizeMode: 'cover',
    height: 130,
    width: 130,
    alignItems: 'center',
  },
  go: {
    //right: 100,
    height: 10,
    width: 10,
    alignItems: 'center',
    justifycontent: 'flex-end',
    position: 'absolute',
    right: 4,
  },
  setting: {
    position: 'absolute',
    top: 40,
    right: 30,
    height: 40,
    width: 40,
    alignItems: 'center',
  },
  text4: {
    fontSize: 17,
    // alignSelf: 'flex-start',
    // left: 110,
    textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
  },
  texts1: {
    alignContent: 'center',
    paddingBottom: 30,
    right: 80,
    //fontSize: 15,
    // alignSelf: 'flex-start',
    // left: 110,
    //textAlign: 'center',
    color: 'white',
    fontWeight: 'bold',
  },
  rectangle: {
    position: 'absolute',
    top: 0,
    borderBottomRightRadius: 80,
    width: 410,
    height: 250,
    marginBottom: 20,
    backgroundColor: '#E35205',
  },
});

export default StyleMaincomponent;
